name: Build Unsigned iOS IPA

on:
  workflow_dispatch: # Cho phép bạn bấm nút Run thủ công trên GitHub mỗi khi muốn build

jobs:
  build_ios:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
      - name: Tải mã nguồn về máy ảo
        uses: actions/checkout@v4

      - name: Cài đặt Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Cài đặt Dependencies
        run: flutter pub get

      - name: Build thư mục iOS (Không cần chứng chỉ)
        run: flutter build ios --release --no-codesign

      - name: Đóng gói thành file IPA (Kỹ thuật Payload)
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -R Runner.app Payload
          zip -r -q app.ipa Payload

      - name: Tải file IPA lên GitHub để bạn Download
        uses: actions/upload-artifact@v4
        with:
          name: ticketmanagement-unsigned-ipa
          path: build/ios/iphoneos/app.ipa
